
python is an advanced programming language. it's designed for human, not machine.
Kernel is an interpreter or translator generating machine language from advanced languages like python.
python is open-source and a lot of people are contributing to python through making third-party
libraries/ packages. A package is a collection of a series of modules and one module is one .py file.
To manage those third-party packages, conda appears to work in the form of environment of receiving and removing packages.



In [ ]:
# number operators: python -- matlab
# 加法 addition + -- +
# 减法 subtraction - -- +
# 乘法 multiplication * -- +
# 除法 division with decimal / -- /

# 乘方 exponentiation ** -- ^
# 整除 round division // -- ceil, floor, fix, round
# 余数 remainder % -- rem, mod

# no unary increment and decrement ++ --


In [9]:
print(2**3, 5/3, 5//3, 5%3)

8 1.6666666666666667 1 2


In [15]:
# boolean operations: python -- matlab
# and -- &/&& 
# or -- |/||
# not -- ~
# != -- ~=

In [17]:
a = True
b = False
print(a and b, a or b, not b, a != b)

False True True True


In [19]:
# list
l1 = [1, 2, 3, 4, 5]
print(type(l1))
print(l1[1:4]) # accessing ans slicing 
l2 = [i**2 for i in l1] # comprehension
print(l2)

<class 'list'>
[2, 3, 4]
[1, 4, 9, 16, 25]


In [20]:
# dictionary
d1 = {"x": 1, "y": 2}
d2 = dict(x=1, y=2)
print(type(d2))  # dict
print(d1["x"])  # accessing, no slicing
print(d2)
d3 = {d1[i]: i for i in d1.keys()}
print(d3)

<class 'dict'>
1
{'x': 1, 'y': 2}
{1: 'x', 2: 'y'}


In [22]:
# set
s1 = {1, "2", 3, "a"}  # no order, cannot be accessed
print(type(s1))  # set
s2 = {i for i in s1 if isinstance(i, str)}
print(s2)

<class 'set'>
{'2', 'a'}


In [21]:
# tuple
t1 = (1, 2, 3, 4)
t2 = tuple(range(4))
print(t2)
print(type(t2))  # tuple
print(t1[:-1])  # accessing, no comprehension -- Matlab uses 'end' and cannot omit the start and end.
a, b, c, d = t1  # unpacking a tuple
print(a, b, c, d)

(0, 1, 2, 3)
<class 'tuple'>
(1, 2, 3)
1 2 3 4


In [26]:
# function
def test_func(x, *apa, y=1, **aka):
    print(x)  # positional argument
    print(apa[0])  # additional/extra positional arguments, tuple
    print(y)  # keyword argument
    print(aka['z'])  # additional/extra keyword arguments, dictionary
    
test_func(2, 2, y=4, z=5)

2
2
4
5


In [34]:
# class
from torch import nn
class TestClass(nn.Module):
    def __init__(self, x, y):
        super().__init__()
        self.x = x
        self.y = y

    def __iter__(self):  # used in loop
        self.n = 0
        return self  # the self here is an iterator

    def __next__(self):  # control iterator defined in __iter__
        if self.n < self.x:
            r = 2*self.n
            self.n += 1
            return r
        else:
            raise StopIteration  # end control

    def __getitem__(self, item):  # used with []
        print(f'get element [{item}]')

    def __call__(self):  # function method, used with ()
        print(self.x-self.y)

    def forward(self):  # function method, regard object/instance of this class as a function
        print(self.x+self.y)

    def test(self):
        print(f'this is an ordinary method')
        
obj = TestClass(4, 8)
for idx, i in enumerate(obj):
    print(f'the {idx}th element is {i}')
obj[4]
obj()  # run __call__ instead of forward, why? call has higher priority over forward which is based on nn.Module
obj.test()

the 0th element is 0
the 1th element is 2
the 2th element is 4
the 3th element is 6
get element [4]
-4
this is an ordinary method


In [42]:

# numpy，ndarray: .shape, .dtype, np.newaxis, np.expand_dims, np.squeeze, np.reshape, .astype()
import numpy as np
print('numpy test')
a = np.random.rand(2, 2)  # torch uses torch.rand, matlab uses "rand"
b = np.random.randn(2, 2) # torch uses torch.randn, matlab uses "randn"
print(f'unifrom distributiion:\n {a}')
print(f'standard normal distribution: \n {b}')

print(f'shape: {a.shape}')  # get the shape of an adarray
print(f'rank: {len(a.shape)}')
print(f'data type: {a.dtype}')  # get the data type of elements
print(a[:, 1])  # accessing and slicing, rank:1
print(np.expand_dims(a[:, 1], axis=1))  # add a dimension
print(a[:, 1][:, np.newaxis]) # another way of adding dimensions

print(a[:, 1:2])  # accessing and slicing, rank:2
print(np.squeeze(a[:, 1:2], axis=1))  # remove dimension
x = np.ones((2, 2))  # different from rand and randn
print(x+x)  # addition
print(x*x)  # element-wise multiplication -- matlab uses ".*"
print(x@x)  # matrix multiplication
print(x+np.ones((2, 1)))  # broadcasting -- matlab also has broadcasting function
print(x/np.ones((1, 2)))  # broadcasting 
print(np.reshape(x, (1, -1))) # reshape


numpy test
unifrom distributiion:
 [[0.06012417 0.97707551]
 [0.54631934 0.0596382 ]]
standard normal distribution: 
 [[-0.82842995 -0.57889703]
 [-0.68192232 -0.39089931]]
shape: (2, 2)
rank: 2
data type: float64
[0.97707551 0.0596382 ]
[[0.97707551]
 [0.0596382 ]]
[[0.97707551]
 [0.0596382 ]]
[[0.97707551]
 [0.0596382 ]]
[0.97707551 0.0596382 ]
[[2. 2.]
 [2. 2.]]
[[1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]]
[[2. 2.]
 [2. 2.]]
[[1. 1.]
 [1. 1.]]
[[1. 1. 1. 1.]]


In [50]:

# pytorch, tensor: .shape, .dtype, torch.unsqueeze, torch.squeeze, torch.reshape, .view(), .type()
import torch
print('torch test')
a = torch.rand((2, 2))
b = torch.randn((2, 2))
print(f'a: \n{a}')
print(f'b: \n{b}')
print(type(a), a.shape, a.dtype, len(a.shape))
print(a[1, :])
print(torch.unsqueeze(a[1, :], dim=0))
print(a[1:2, :])
print(torch.squeeze(a[1:2, :], dim=0))
print(torch.squeeze(a[1:2, :]))
x = torch.ones(2, 2)
print(x)
print(a+x)
print(a*x)
print(x@x)  # matrix multiplication
print(a+torch.ones(1, 2))
print(a+torch.ones(2))
print(torch.ones(2, 1))  # broadcasting


torch test
a: 
tensor([[0.7648, 0.3996],
        [0.9057, 0.7860]])
b: 
tensor([[ 0.1783,  1.5244],
        [-0.5184,  0.8942]])
<class 'torch.Tensor'> torch.Size([2, 2]) torch.float32 2
tensor([0.9057, 0.7860])
tensor([[0.9057, 0.7860]])
tensor([[0.9057, 0.7860]])
tensor([0.9057, 0.7860])
tensor([0.9057, 0.7860])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1.7648, 1.3996],
        [1.9057, 1.7860]])
tensor([[0.7648, 0.3996],
        [0.9057, 0.7860]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[1.7648, 1.3996],
        [1.9057, 1.7860]])
tensor([[1.7648, 1.3996],
        [1.9057, 1.7860]])
tensor([[1.],
        [1.]])


In [57]:
# automatic differentiation of torch
print('test autograd')
x = torch.ones((2, 2), requires_grad=True)  # require_grad's default value is False, so enable it
print(x)
y = x**3  # (1, 2)
print(y)
z = torch.sum(y)  # single value
print(z)

z.backward()  # calculate the gradient of leaf tensors, x is a leaf, y is not s leaf.
print(f'the gradient of z to x:\n{x.grad}')
x.grad.zero_()  # set the gradient as zero
print(f'the gradient of z to x after setting zero:\n{x.grad}')
print(f'the gradient of z to y:\n{y.grad}')  # y is not a leaf, so this way cannot reach y gradient.

# print('another way to get gradients')
# x_grad = torch.autograd.grad(z, x)  # apply torch.autograd.grad which can be only applied to scalar
# y_grad = torch.autograd.grad(z, y)
# print(f'the gradient of z to x:\n{x_grad}')
# print(f'the gradient of z to y:\n{y_grad}')


test autograd
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)
tensor(4., grad_fn=<SumBackward0>)
the gradient of z to x:
tensor([[3., 3.],
        [3., 3.]])
the gradient of z to x after setting zero:
tensor([[0., 0.],
        [0., 0.]])
the gradient of z to y:
None
